CLASS_BACKGROUND = "Background"
CLASS_POLYMER_COATING = "Polymer Coating"
CLASS_VOIDS = "Voids"
CLASS_FIBER_EPOXY_MATRIX = "Fiber-Epoxy Matrix"


CLASS_MAP = {
    CLASS_BACKGROUND: 0,
    CLASS_POLYMER_COATING: 1,
    CLASS_VOIDS: 2,
    CLASS_FIBER_EPOXY_MATRIX: 3
}
